export enum ENV_ENUM {
  APP_PORT = 'APP_PORT',
  DATABASE_NAME = 'DATABASE_NAME-db',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  NODE_ENV = 'NODE_ENV',
  CLIENT_URI = 'CLIENT_URI',
  SALT = 'SALT',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
}
