version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_PASSWORD: postgres-pwd
      POSTGRES_USER: postgres-usr
